#!/bin/bash -e

if [ ! -d /var/run/named ]; then
    mkdir -p /var/run/named
    chmod 775 /var/run/named
    chown root:bind /var/run/named
fi

if [ ! -d /var/cache/bind ]; then
    mkdir /var/cache/bind
    chmod 775 /var/cache/bind
    chown root:bind /var/cache/bind
fi

if [ ! -s /etc/bind/rndc.key ]; then
    rndc-confgen -r /dev/urandom -a
fi

if [ ! -s /etc/bind/db.255 ]; then
    cp /etc/bind/db.0 /etc/bind/db.255
fi

chmod 2755 /etc/bind
chmod 644 /etc/bind/*
chown -R root:root /etc/bind
chown root:bind /etc/bind/named.conf
chown root:bind /etc/bind/named.conf.default-zones
chown root:bind /etc/bind/named.conf.local
chown root:bind /etc/bind/named.conf.options

chmod 640 /etc/bind/rndc.key
chown bind:bind /etc/bind/rndc.key

exec supervisord
